name: gitstars
description: A Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  intl: ^0.16.1
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.2+1
  flutter_html: ^1.0.2

  get: 3.17.1
  get_storage: ^1.3.2
  graphql: ^4.0.1

  # CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets section:
  assets:
    - assets/icons/
    - test/mock/data/

  # Fonts Section:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserratregular.ttf
        - asset: assets/fonts/montserratbold.ttf
          weight: 700
